"""initial migration.

Revision ID: 9caed55189b5
Revises: 
Create Date: 2024-08-07 23:36:14.697785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caed55189b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('cid', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('college', sa.Text(), nullable=False),
    sa.Column('dept', sa.Text(), nullable=False),
    sa.Column('course_title', sa.String(), nullable=False),
    sa.Column('course_desc', sa.Text(), nullable=False),
    sa.Column('sgd', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_course_desc'), ['course_desc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_course_desc'))

    op.drop_table('course')
    # ### end Alembic commands ###
